### PR TITLE
Support underscored_manytomany_fields

### PR DESCRIPTION
**Pull request by davidrenne**

### CODE REVIEW

**Comment by vtainio** [comment]
@davidrenne Looks good to me. Thanks a lot for the contribution!

I will let @mixman browse through it before merging, since he wrote the thing. He should be back from vacation next week.

**Comment by davidrenne** [comment]
Hey thanks man!

—
Dave

**Comment by mixman** [comment]
I added the option to provide your own function for securing views. For your use-case something like this should work:

```
# settings
DJANGO_HISTORY_VIEW_PERMISSION = ('myproject.views','get_permission')
# myproject/views.py
def get_permission(request):
 return request.user.is_staff
```

**Comment by davidrenne** [comment]
FACEBOOK LIKE

**Pull request merged**
